exclude_patterns = [
  "dist/**",
  "node_modules/**",
  "ci/**",
  "tests/**",
  "build/**",
  "astro/**"
]

[smells]
mode = "block"

[smells.identical_code]
enabled = false

[smells.similar_code]
enabled = false

[smells.file_complexity]
threshold = 170

[smells.function_complexity]
threshold = 120

[smells.return_statements]
threshold = 20

[smells.boolean_logic]
threshold = 10

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[[plugin]]
name = "eslint"
version = "9.39.4"
package_file = "package.json"

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "zizmor"

# Triage rules to ignore specific renegade rules
[[triage]]
match.plugins = ["zizmor"]
match.rules = [
  "zizmor:zizmor/unpinned-uses",
  "zizmor:zizmor/cache-poisoning",
  "zizmor:zizmor/artipacked"
]
set.ignored = true